name: Publish to preprod

on:
  push:
    branches: ["master"]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check linting
        run: npm install
  build:
    name: Build static website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check linting
        run: npm run build
  deploy:
    name: Deploy the website in preproduction
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: 47ng/actions-clever-cloud@v1.2.0
      with:
        appID: ${{ secrets.CLEVER_APP_ID_PREPROD }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}