name: Publish to preprod

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy the website in preproduction
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build static website
      run: npm install && npm run build
    - name: Deploy the website in preproduction
      working-directory: dist
      run: |
        clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
        clever link ${{ secrets.CLEVER_APP_ID_PREPROD }}
        clever deploy --force