name: Publish to preprod

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy the website in preproduction
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build static website
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: npm install && npm run build
    - name: Deploy the website in preproduction
      working-directory: dist
      run: |
        npm install -g clever-tools 
        git config --global user.email ${{ secrets.GIT_EMAIL }}
        git config --global user.name ${{ secrets.GIT_NAME }}
        git init
        git remote add preprod git+ssh://git@push-n2-par-clevercloud-customers.services.clever-cloud.com/${{ secrets.CLEVER_APP_ID_PREPROD }}.git
        git add -f .
        git commit -m "chore: forward changed to preprod"
        clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
        clever link ${{ secrets.CLEVER_APP_ID_PREPROD }}
        clever deploy --force